function execute() {
    return Response.success([
        {title: "诸天流 - 新入库", input: "chư thiên&new", script: "search.js"},
        {title: "诸天流 - 新更新", input: "chư thiên&update", script: "search.js"},
        {title: "诸天流 - 总阅读量", input: "chư thiên&view", script: "search.js"},
        {title: "诸天流 - 本周阅读量", input: "chư thiên&viewweek", script: "search.js"},
        {title: "诸天流 - 今日阅读量", input: "chư thiên&viewday", script: "search.js"},
        {title: "诸天流 - 点赞数", input: "chư thiên&like", script: "search.js"},
        {title: "诸天流 - 关注数", input: "chư thiên&following", script: "search.js"},
        {title: "诸天流 - 收藏数", input: "chư thiên&bookmarked", script: "search.js"},

        {title: "聊天群 - 新入库", input: "chat group&new", script: "search.js"},

        {title: "官场职场 - 新更新", input: "quantruongcholamviec,", script: "tag.js"},
        {title: "武侠 - 新更新", input: "vuhiep,", script: "tag.js"},
        {title: "时空 - 新更新", input: "xuyenquathoikhong,", script: "tag.js"},
        {title: "同人 - 新更新", input: "dongnhan,", script: "tag.js"},
        {title: "玄幻魔法 - 新更新", input: "huyenhuyenmaphap,", script: "tag.js"},

        {title: "新入库", input: "&new", script: "search.js"},
        {title: "新更新", input: "&update", script: "search.js"},
        {title: "本周阅读量", input: "&viewweek", script: "search.js"},
        {title: "今日阅读量", input: "&viewday", script: "search.js"},
        {title: "总阅读量", input: "&view", script: "search.js"},
        {title: "点赞数", input: "&like", script: "search.js"},
        {title: "关注数", input: "&following", script: "search.js"},
        {title: "收藏数", input: "&bookmarked", script: "search.js"},
        
        { title: "思路清奇", input: "/思路清奇/{0}/", script: "gen2.js" },
        { title: "穿越", input: "/穿越/{0}/", script: "gen2.js" },
        { title: "轻松", input: "/轻松/{0}/", script: "gen2.js" },
        { title: "系统流", input: "/系统流/{0}/", script: "gen2.js" },
        { title: "重生", input: "/重生/{0}/", script: "gen2.js" },
        { title: "爽文", input: "/爽文/{0}/", script: "gen2.js" },
        { title: "无敌流", input: "/无敌流/{0}/", script: "gen2.js" },
        { title: "种田", input: "/种田/{0}/", script: "gen2.js" },
        { title: "逆袭", input: "/逆袭/{0}/", script: "gen2.js" },
        { title: "经营", input: "/经营/{0}/", script: "gen2.js" },
        { title: "杀伐果断", input: "/杀伐果断/{0}/", script: "gen2.js" },
        { title: "快节奏", input: "/快节奏/{0}/", script: "gen2.js" },
        { title: "日常文", input: "/日常文/{0}/", script: "gen2.js" },
        { title: "架空", input: "/架空/{0}/", script: "gen2.js" },
        { title: "打脸", input: "/打脸/{0}/", script: "gen2.js" },
        { title: "萌宝", input: "/萌宝/{0}/", script: "gen2.js" },
        { title: "校园", input: "/校园/{0}/", script: "gen2.js" },
        { title: "无限流", input: "/无限流/{0}/", script: "gen2.js" },
        { title: "智商在线", input: "/智商在线/{0}/", script: "gen2.js" },
        { title: "冷静", input: "/冷静/{0}/", script: "gen2.js" },
        { title: "空间", input: "/空间/{0}/", script: "gen2.js" },
        { title: "异能", input: "/异能/{0}/", script: "gen2.js" },
        { title: "诸天流", input: "/诸天流/{0}/", script: "gen2.js" },
        { title: "快穿", input: "/快穿/{0}/", script: "gen2.js" },
        { title: "脑洞大", input: "/脑洞大/{0}/", script: "gen2.js" },
        { title: "金手指", input: "/金手指/{0}/", script: "gen2.js" },
        { title: "穿书", input: "/穿书/{0}/", script: "gen2.js" },
        { title: "大佬", input: "/大佬/{0}/", script: "gen2.js" },
        { title: "文娱", input: "/文娱/{0}/", script: "gen2.js" },
        { title: "娱乐圈", input: "/娱乐圈/{0}/", script: "gen2.js" },
        { title: "赚钱", input: "/赚钱/{0}/", script: "gen2.js" },
        { title: "强者归来", input: "/强者归来/{0}/", script: "gen2.js" },
    ]);
}
